version: "3.9"
services:
  kies-dashboard:
    build: .
    image: kieserver-dashboard-2-charts
    container_name: kieserver-dashboard-2-charts
    network_mode: "host"
    environment:
      - LOG_DIR=/home/ruben/Git/Redhat-DecisionManager/01-KieserverLogs/prod
      - PORT=8081
      - TEMPLATE_DIR=/app/templates
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /home/ruben/Git/Redhat-DecisionManager/01-KieserverLogs/prod:/home/ruben/Git/Redhat-DecisionManager/01-KieserverLogs/prod
      - /home/ruben/Git/kieserver-dashboard-2-charts/templates:/app/templates
    restart: always

